language: objective-c
osx_image: xcode9.4 

before_install:
  - gem install xcpretty-travis-formatter;
  - gem install cocoapods --no-document --quiet;
  - pod install --repo-update;

script:
  - set -o pipefail && xcodebuild -workspace LayoutFrameworkBenchmark.xcworkspace -scheme LayoutFrameworkBenchmark -sdk iphonesimulator11.2 -destination 'platform=iOS Simulator,name=iPhone 6' build | xcpretty -f `xcpretty-travis-formatter`
